# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/{{namespace}}.Api.sln'
  testProject: '**/*Test.csproj'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet Cli

- task: NuGetCommand@2
  displayName: Restore packages
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: Unit testing
  inputs:
    command: 'test'
    arguments: '/p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura /p:Exclude="[*.*.EntityFramework]*"'
    projects: '$(testProject)'

- task: PublishCodeCoverageResults@1
  displayName: Publish coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/*coverage*.xml'

- task: DotNetCoreCLI@2
  displayName: Publish solution
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish solution artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'